### Model Pipeline

1. Raw table_data (string)

        ↓ linearize

2. Linearized text (string)

        ↓ tokenizer.encode()

3. Token IDs (integers)

        ↓ model's embedding layer (learned lookup table, inside the model)

4. Token embeddings + positional embeddings

        ↓ encoder self-attention layers (bidirectional)

5. Encoder hidden states (contextualized representations, one vector per input token)

        ↓ fed into every decoder layer via cross-attention

6. Decoder (causal self-attention + cross-attention into step 5)

        ↓ generates one token at a time, autoregressively

7. Output logits → softmax → generated token

        ↓ repeat step 6-7 until <eos>
        
8. Decoded text = generated financial commentary

execution order:

1. Setup and preprocessing  
2. Shared datasets and evaluation utilities  
3. Zero-shot T5-small baseline  
4. Fine-tuned T5-small  
5. Combined model-level metrics and prediction-level outputs

### Installs and Imports

In [1]:
!pip install -q  -U transformers
!pip install -q -U datasets
!pip install -q -U evaluate
!pip install -q tokenizers
!pip install rouge_score

In [22]:
!pip install rouge_score
!pip install sacrebleu
!pip install meteor-score
!pip install bert-score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=a150b04419923317734aff0adeec4589586671680c196e53233494ac88e98c7b
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2
Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.1.1)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.8 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0
ERROR: Could not find a version that satisfies the requirement meteor-score (from versions: none)
ERROR: No matching distribution found for meteor-score
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.11.0+cu128)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.14.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2026.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.23.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.6.17)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.0.0->bert-score) (1.5.6)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=3.0.0->bert-score) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=3.0.0->bert-score) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=3.0.0->bert-score) (0.1.2)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 3.7 MB/s eta 0:00:00
Installing collected packages: bert-score
Successfully installed bert-score-0.3.13

In [2]:
import os
import re
import json
import random
import numpy as np
import pandas as pd
import torch

In [3]:
from datasets import Dataset, DatasetDict
import evaluate

In [5]:
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    EarlyStoppingCallback,
)

In [4]:
import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download("punkt")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [6]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

In [7]:
print("PyTorch version:", torch.__version__)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.11.0+cu128
Device: cuda
GPU: Tesla T4

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Using preprocessing notebook to use the same variables and features.

In [9]:
BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/266/266_final_project"
PREPROCESSING_SCRIPT = os.path.join(BASE_DIR, "train_splitEDA.py")

# This script must create train_df, test_df, summarize_market_table, and token_length.
%run -i "$PREPROCESSING_SCRIPT"

print("Train rows:", len(train_df))
print("Test rows:", len(test_df))

PyTorch version: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Train shape: (3143, 7)
Test shape: (795, 7)
['source', 'market', 'date', 'instruction', 'table_data', 'report', 'prompts']

,source,market,date,instruction,table_data,report,prompts
0,totalfarmmarketing,cattle,2021-12-02,Please act as an expert financial market analy...,Date Pro...,Cattle futures posted moderate to strong gains...,{'instruction': 'Please act as an expert finan...
1,totalfarmmarketing,cattle,2022-01-14,Please act as an expert financial market analy...,Date Pro...,"Cattle prices are trying to turn higher, as th...",{'instruction': 'Please act as an expert finan...

0
0
count    3143.000000
mean      536.570474
std       363.832138
min        12.000000
25%       271.000000
50%       451.000000
75%       690.000000
max      2243.000000
Name: report, dtype: float64
      Date                                 Product Name Symbol   Open   High    Low  Close  Volume
2021-11-02  Live Cattle Future (front month) (December)   LEZ1 128.90 130.43 128.88 129.95 21275.0
2021-11-03  Live Cattle Future (front month) (December)   LEZ1 130.90 132.40 130.62 131.65 27572.0
2021-11-04  Live Cattle Future (front month) (December)   LEZ1 131.57 132.00 130.55 130.62 23398.0
2021-11-05  Live Cattle Future (front month) (December)   LEZ1 130.85 131.93 130.68 131.80 31050.0
2021-11-08  Live Cattle Future (front month) (December)   LEZ1 131.70 132.50 131.70 132.10 30902.0
2021-11-09  Live Cattle Future (front month) (December)   LEZ1 131.88 132.38 131.40 132.20 30503.0
2021-11-10  Live Cattle Future (front month) (December)   LEZ1 131.90 132.38 131.30 132.00 31903.0
2021-11-11  Live Cattle Future (front month) (December)   LEZ1 132.15 132.32 131.38 131.88 25671.0
2021-11-12  Live Cattle Future (front month) (December)   LEZ1 131.90 132.62 131.48 132.12 21703.0
2021-11-15  Live Cattle Future (front month) (December)   LEZ1 131.78 132.30 131.50 131.78 14062.0
2021-11-16  Live Cattle Future (front month) (December)   LEZ1 131.78 132.18 131.68 131.72 10213.0
2021-11-17  Live Cattle Future (front month) (December)   LEZ1 131.93 132.38 131.80 132.22 13364.0
2021-11-18  Live Cattle Future (front month) (December)   LEZ1 132.45 133.28 132.40 133.15  9596.0
2021-11-19  Live Cattle Future (front month) (December)   LEZ1 133.25 133.68 133.00 133.52  8783.0
2021-11-22  Live Cattle Future (front month) (December)   LEZ1 133.82 134.52 133.68 134.43  9629.0
2021-11-23  Live Cattle Future (front month) (December)   LEZ1 134.48 135.57 134.22 135.40  9547.0
2021-11-24  Live Cattle Future (front month) (December)   LEZ1 136.05 137.98 136.00 137.90 16978.0
2021-11-26  Live Cattle Future (front month) (December)   LEZ1 136.40 138.35 136.28 138.10  8984.0
2021-11-29  Live Cattle Future (front month) (December)   LEZ1 138.25 139.12 136.62 136.93 12045.0
2021-11-30  Live Cattle Future (front month) (December)   LEZ1 136.50 136.90 135.55 135.88  9845.0
2021-12-01  Live Cattle Future (front month) (December)   LEZ1 136.57 137.43 135.90 136.00  9143.0
2021-12-02  Live Cattle Future (front month) (December)   LEZ1 136.00 138.05 135.98 137.65  9140.0
2021-11-02 Live Cattle Future (second month) (February)   LEG2 134.10 135.68 134.05 135.22 12106.0
2021-11-03 Live Cattle Future (second month) (February)   LEG2 136.02 137.20 135.75 136.65 16056.0
2021-11-04 Live Cattle Future (second month) (February)   LEG2 136.50 137.00 135.75 135.85 13495.0
2021-11-05 Live Cattle Future (second month) (February)   LEG2 136.15 137.20 135.93 137.12 24736.0
2021-11-08 Live Cattle Future (second month) (February)   LEG2 137.00 137.68 137.00 137.12 28992.0
2021-11-09 Live Cattle Future (second month) (February)   LEG2 136.85 137.05 136.40 136.70 28356.0
2021-11-10 Live Cattle Future (second month) (February)   LEG2 136.55 137.00 136.10 136.82 26433.0
2021-11-11 Live Cattle Future (second month) (February)   LEG2 137.00 137.25 136.02 136.40 25667.0
2021-11-12 Live Cattle Future (second month) (February)   LEG2 136.32 136.55 135.40 136.10 23463.0
2021-11-15 Live Cattle Future (second month) (February)   LEG2 135.75 136.68 135.50 136.32 16765.0
2021-11-16 Live Cattle Future (second month) (February)   LEG2 136.25 136.52 135.98 136.10 14503.0
2021-11-17 Live Cattle Future (second month) (February)   LEG2 136.00 136.45 135.88 136.40 16228.0
2021-11-18 Live Cattle Future (second month) (February)   LEG2 136.78 137.45 136.57 137.25 19445.0
2021-11-19 Live Cattle Future (second month) (February)   LEG2 137.22 137.78 137.05 137.70 15324.0
2021-11-22 Live Cattle Future (second month) (February)   LEG2 137.90 139.05 137.85 138.98 22298.0
2021-11-23 Live Cattle Future (second month) (February)   LEG2 138.93 139.65 138.78 139.43 20887.0
2021-11-24 Live Cattle Future (second month) (February)   LEG2 139.65 141.07 139.60 140.88 28947.0
2021-11-26 Live Cattle Future (second month) (February)   LEG2 138.95 141.45 138.68 141.20 25464.0
2021-11-29 Live Cattle Future (second month) (February)   LEG2 141.35 141.85 138.95 139.30 30477.0
2021-11-30 Live Cattle Future (second month) (February)   LEG2 138.72 139.25 137.35 137.90 30074.0
2021-12-01 Live Cattle Future (second month) (February)   LEG2 138.50 139.75 138.18 138.60 24697.0
2021-12-02 Live Cattle Future (second month) (February)   LEG2 138.25 139.98 138.25 139.57 19021.0
2021-11-02     Live Cattle Future (third month) (April)   LEJ2 136.72 138.35 136.72 138.18  6127.0
2021-11-03     Live Cattle Future (third month) (April)   LEJ2 138.88 139.80 138.55 139.43  9207.0
2021-11-04     Live Cattle Future (third month) (April)   LEJ2 139.18 139.70 138.68 138.82  5810.0
2021-11-05     Live Cattle Future (third month) (April)   LEJ2 138.98 140.02 138.72 140.00  9897.0
2021-11-08     Live Cattle Future (third month) (April)   LEJ2 139.85 140.68 139.80 140.40 10908.0
2021-11-09     Live Cattle Future (third month) (April)   LEJ2 140.00 140.45 139.68 140.25 10357.0
2021-11-10     Live Cattle Future (third month) (April)   LEJ2 140.05 140.38 139.52 140.32  9991.0
2021-11-11     Live Cattle Future (third month) (April)   LEJ2 140.35 140.50 139.75 140.25 12006.0
2021-11-12     Live Cattle Future (third month) (April)   LEJ2 140.02 140.48 139.25 139.90 11567.0
2021-11-15     Live Cattle Future (third month) (April)   LEJ2 139.60 140.25 139.30 139.98  7322.0
2021-11-16     Live Cattle Future (third month) (April)   LEJ2 139.88 140.28 139.75 139.80  5584.0
2021-11-17     Live Cattle Future (third month) (April)   LEJ2 139.80 140.32 139.70 140.28  7378.0
2021-11-18     Live Cattle Future (third month) (April)   LEJ2 140.40 141.00 140.38 140.88  8229.0
2021-11-19     Live Cattle Future (third month) (April)   LEJ2 140.88 141.40 140.78 141.30  9328.0
2021-11-22     Live Cattle Future (third month) (April)   LEJ2 141.40 142.30 141.28 142.28 10352.0
2021-11-23     Live Cattle Future (third month) (April)   LEJ2 142.00 142.95 142.00 142.80 10658.0
2021-11-24     Live Cattle Future (third month) (April)   LEJ2 143.00 144.10 142.78 143.90 12251.0
2021-11-26     Live Cattle Future (third month) (April)   LEJ2 142.30 144.15 142.05 143.85 10517.0
2021-11-29     Live Cattle Future (third month) (April)   LEJ2 144.00 144.60 142.07 142.52 15244.0
2021-11-30     Live Cattle Future (third month) (April)   LEJ2 141.95 142.60 140.43 141.07 13608.0
2021-12-01     Live Cattle Future (third month) (April)   LEJ2 141.82 142.62 141.32 141.78  9946.0
2021-12-02     Live Cattle Future (third month) (April)   LEJ2 141.52 143.02 141.48 142.60  8732.0
2021-11-02 Feeder Cattle Future (front month) (January)   GFF2 152.90 157.15 152.78 157.02  7478.0
2021-11-03 Feeder Cattle Future (front month) (January)   GFF2 157.43 160.15 157.43 159.22  6857.0
2021-11-04 Feeder Cattle Future (front month) (January)   GFF2 159.05 159.70 158.07 158.18  3955.0
2021-11-05 Feeder Cattle Future (front month) (January)   GFF2 158.30 159.80 157.72 159.60  4437.0
2021-11-08 Feeder Cattle Future (front month) (January)   GFF2 159.68 160.60 159.02 160.30  5907.0
2021-11-09 Feeder Cattle Future (front month) (January)   GFF2 160.60 160.60 158.65 159.80  4473.0
2021-11-10 Feeder Cattle Future (front month) (January)   GFF2 159.35 159.38 157.78 158.05  4322.0
2021-11-11 Feeder Cattle Future (front month) (January)   GFF2 158.25 159.40 157.50 159.07  4011.0
2021-11-12 Feeder Cattle Future (front month) (January)   GFF2 159.10 159.18 156.80 157.72  3954.0
2021-11-15 Feeder Cattle Future (front month) (January)   GFF2 157.65 158.75 156.88 158.48  2595.0
2021-11-16 Feeder Cattle Future (front month) (January)   GFF2 158.50 159.60 158.35 159.28  3814.0
2021-11-17 Feeder Cattle Future (front month) (January)   GFF2 159.25 159.50 157.88 158.93  3710.0
2021-11-18 Feeder Cattle Future (front month) (January)   GFF2 159.00 161.85 158.65 161.38  6035.0
2021-11-19 Feeder Cattle Future (front month) (January)   GFF2 161.48 162.07 160.75 160.93  4132.0
2021-11-22 Feeder Cattle Future (front month) (January)   GFF2 160.78 161.98 160.10 161.70  3024.0
2021-11-23 Feeder Cattle Future (front month) (January)   GFF2 161.98 164.75 161.85 164.38  6067.0
2021-11-24 Feeder Cattle Future (front month) (January)   GFF2 164.68 167.22 164.22 166.92  5632.0
2021-11-26 Feeder Cattle Future (front month) (January)   GFF2 164.08 168.18 164.00 167.15  5536.0
2021-11-29 Feeder Cattle Future (front month) (January)   GFF2 167.50 168.30 165.18 165.72  6511.0
2021-11-30 Feeder Cattle Future (front month) (January)   GFF2 165.20 167.10 163.38 164.85  7207.0
2021-12-01 Feeder Cattle Future (front month) (January)   GFF2 165.00 166.50 164.92 165.82  4498.0
2021-12-02 Feeder Cattle Future (front month) (January)   GFF2 165.40 165.92 164.95 165.78  4289.0
2021-11-02  Feeder Cattle Future (second month) (March)   GFH2 154.45 158.22 154.00 158.00  4081.0
2021-11-03  Feeder Cattle Future (second month) (March)   GFH2 158.48 160.85 158.22 160.15  2704.0
2021-11-04  Feeder Cattle Future (second month) (March)   GFH2 160.15 160.57 159.22 159.32  1970.0
2021-11-05  Feeder Cattle Future (second month) (March)   GFH2 159.38 160.90 158.93 160.78  2433.0
2021-11-08  Feeder Cattle Future (second month) (March)   GFH2 160.90 161.60 160.28 161.40  2113.0
2021-11-09  Feeder Cattle Future (second month) (March)   GFH2 161.20 161.48 159.93 161.02  2331.0
2021-11-10  Feeder Cattle Future (second month) (March)   GFH2 160.48 160.65 159.20 159.57  3059.0
2021-11-11  Feeder Cattle Future (second month) (March)   GFH2 159.52 160.93 159.05 160.45  2715.0
2021-11-12  Feeder Cattle Future (second month) (March)   GFH2 160.45 160.45 158.12 159.18  2246.0
2021-11-15  Feeder Cattle Future (second month) (March)   GFH2 158.70 160.05 158.32 159.88  1238.0
2021-11-16  Feeder Cattle Future (second month) (March)   GFH2 159.95 161.02 159.80 160.90  1714.0
2021-11-17  Feeder Cattle Future (second month) (March)   GFH2 161.00 161.18 159.48 161.10  2037.0
2021-11-18  Feeder Cattle Future (second month) (March)   GFH2 161.00 163.78 160.68 163.55  3218.0
2021-11-19  Feeder Cattle Future (second month) (March)   GFH2 163.70 164.12 163.07 163.38  2613.0
2021-11-22  Feeder Cattle Future (second month) (March)   GFH2 163.30 164.25 162.60 164.10  1753.0
2021-11-23  Feeder Cattle Future (second month) (March)   GFH2 164.22 166.05 164.00 165.68  2922.0
2021-11-24  Feeder Cattle Future (second month) (March)   GFH2 166.00 167.95 165.45 167.90  3250.0
2021-11-26  Feeder Cattle Future (second month) (March)   GFH2 165.28 168.70 165.18 167.98  2833.0
2021-11-29  Feeder Cattle Future (second month) (March)   GFH2 167.98 169.08 165.98 166.55  3797.0
2021-11-30  Feeder Cattle Future (second month) (March)   GFH2 166.00 167.82 165.05 166.50  4688.0
2021-12-01  Feeder Cattle Future (second month) (March)   GFH2 166.52 168.22 166.52 167.90  3616.0
2021-12-02  Feeder Cattle Future (second month) (March)   GFH2 167.50 168.42 166.92 168.32  3149.0
2021-11-02   Feeder Cattle Future (third month) (April)   GFJ2 158.25 161.68 157.82 161.50  1212.0
2021-11-03   Feeder Cattle Future (third month) (April)   GFJ2 161.55 163.80 161.55 163.30   955.0
2021-11-04   Feeder Cattle Future (third month) (April)   GFJ2 163.02 163.55 162.20 162.32  1138.0
2021-11-05   Feeder Cattle Future (third month) (April)   GFJ2 162.30 163.88 161.90 163.72  1365.0
2021-11-08   Feeder Cattle Future (third month) (April)   GFJ2 163.90 164.48 163.20 164.22   934.0
2021-11-09   Feeder Cattle Future (third month) (April)   GFJ2 164.28 164.28 162.70 163.68  1205.0
2021-11-10   Feeder Cattle Future (third month) (April)   GFJ2 163.48 163.48 161.85 162.18  1433.0
2021-11-11   Feeder Cattle Future (third month) (April)   GFJ2 162.38 163.38 161.55 162.95   901.0
2021-11-12   Feeder Cattle Future (third month) (April)   GFJ2 162.90 162.90 160.72 161.78   917.0
2021-11-15   Feeder Cattle Future (third month) (April)   GFJ2 161.32 162.62 160.90 162.32   558.0
2021-11-16   Feeder Cattle Future (third month) (April)   GFJ2 162.48 163.48 162.38 163.43   795.0
2021-11-17   Feeder Cattle Future (third month) (April)   GFJ2 163.30 163.80 162.12 163.72  1015.0
2021-11-18   Feeder Cattle Future (third month) (April)   GFJ2 163.38 166.15 163.38 166.08  1267.0
2021-11-19   Feeder Cattle Future (third month) (April)   GFJ2 166.10 166.50 165.55 165.88  1283.0
2021-11-22   Feeder Cattle Future (third month) (April)   GFJ2 165.55 166.82 165.32 166.70   784.0
2021-11-23   Feeder Cattle Future (third month) (April)   GFJ2 166.82 168.42 166.60 168.02  1119.0
2021-11-24   Feeder Cattle Future (third month) (April)   GFJ2 168.32 169.98 167.65 169.80  1611.0
2021-11-26   Feeder Cattle Future (third month) (April)   GFJ2 167.50 170.40 167.35 169.88  1330.0
2021-11-29   Feeder Cattle Future (third month) (April)   GFJ2 169.88 171.00 167.82 168.58  2057.0
2021-11-30   Feeder Cattle Future (third month) (April)   GFJ2 167.58 169.85 167.25 168.82  2380.0
2021-12-01   Feeder Cattle Future (third month) (April)   GFJ2 168.82 170.70 168.82 170.45  1681.0
2021-12-02   Feeder Cattle Future (third month) (April)   GFJ2 170.00 171.00 169.62 170.90  1288.0

===== EXAMPLE 0 =====
      Date                                 Product Name Symbol   Open   High    Low  Close  Volume
2021-11-02  Live Cattle Future (front month) (December)   LEZ1 128.90 130.43 128.88 129.95 21275.0
2021-11-03  Live Cattle Future (front month) (December)   LEZ1 130.90 132.40 130.62 131.65 27572.0
2021-11-04  Live Cattle Future (front month) (December)   LEZ1 131.57 132.00 130.55 130.62 23398.0
2021-11-05  Live Cattle Future (front month) (December)   LEZ1 130.85 131.93 130.68 131.80 31050.0
2021-11-08  Live Cattle Future (front month) (December)   LEZ1 131.70 132.50 131.70 132.10 30902.0
2021-11-09  Live Cattle Future (front month) (December)   LEZ1 131.88 132.38 131.40 132.20 30503.0
2021-11-10  Live Cattle Future (front month) (December)   LEZ1 131.90 132.38 131.30 132.00 31903.0
2021-11-11  Live Cattle Future (front month) (December)   LEZ1 132.15 132.32 131.38 131.88 25671.0
2021-11-12  Live Cattle Future (front month) (December)   LEZ1 131.90 132.62 131.48 132.12 21703.0
2021-11-15  Live Cattle Future (front month) (December)   LEZ1 131.78 132.30 131.50 131.78 14062.0
2021-11-16  Live Cattle Future (front month) (December)   LEZ1 131.78 132.18 131.68 131.72 10213.0
2021-11-17  Live Cattle Future (front month) (December)   LEZ1 131.93 132.38 131.80 132.22 13364.0
2021-11-18  Live Cattle Future (front month) (December)   LEZ1 132.45 133.28 132.40 133.15  9596.0
2021-11-19  Live Cattle Future (front month) (December)   LEZ1 133.25 133.68 133.00 133.52  8783.0
2021-11-22  Live Cattle Future (front month) (December)   LEZ1 133.82 134.52 133.68 134.43  9629.0
2021-11-23  Live Cattle Future (front month) (December)   LEZ1 134.48 135.57 134.22 135.40  9547.0
2021-11-24  Live Cattle Future (front month) (December)   LEZ1 136.05 137.98 136.00 137.90 16978.0
2021-11-26  Live Cattle Future (front month) (December)   LEZ1 136.40 138.35 136.28 138.10  8984.0
2021-11-29  Live Cattle Future (front month) (December)   LEZ1 138.25 139.12 136.62 136.93 12045.0
2021-11-30  Live Cattle Future (front month) (December)   LEZ1 136.50 136.90 135.55 135.88  9845.0
2021-12-01  Live Cattle Future (front month) (December)   LEZ1 136.57 137.43 135.90 136.00  9143.0
2021-12-02  Live Cattle Future (front month) (December)   LEZ1 136.00 138.05 135.98 137.65  9140.0
2021-11-02 Live Cattle Future (second month) (February)   LEG2 134.10 135.68 134.05 135.22 12106.0
2021-11-03 Live Cattle Future (second month) (February)   LEG2 136.02 137.20 135.75 136.65 16056.0
2021-11-04 Live Cattle Future (second month) (February)   LEG2 136.50 137.00 135.75 135.85 13495.0
2021-11-05 Live Cattle Future (second month) (February)   LEG2 136.15 137.20 135.93 137.12 24736.0
2021-11-08 Live Cattle Future (second month) (February)   LEG2 137.00 137.68 137.00 137.12 28992.0
2021-11-09 Live Cattle Future (second month) (February)   LEG2 136.85 137.05 136.40 136.70 28356.0
2021-11-10 Live Cattle Future (second month) (February)   LEG2 136.55 137.00 136.10 136.82 26433.0
2021-11-11 Live Cattle Future

===== EXAMPLE 1 =====
      Date                                 Product Name Symbol   Open   High    Low  Close  Volume
2021-12-15  Live Cattle Future (front month) (February)   LEG2 138.22 138.25 136.50 136.57 21294.0
2021-12-16  Live Cattle Future (front month) (February)   LEG2 136.62 137.35 135.80 137.05 20002.0
2021-12-17  Live Cattle Future (front month) (February)   LEG2 136.90 137.20 136.00 136.43 18785.0
2021-12-20  Live Cattle Future (front month) (February)   LEG2 135.93 136.55 135.50 135.98 20294.0
2021-12-21  Live Cattle Future (front month) (February)   LEG2 136.28 137.65 135.95 136.93 17615.0
2021-12-22  Live Cattle Future (front month) (February)   LEG2 136.93 137.57 136.70 137.38 13095.0
2021-12-23  Live Cattle Future (front month) (February)   LEG2 137.40 139.72 137.25 139.62 19977.0
2021-12-27  Live Cattle Future (front month) (February)   LEG2 139.60 140.32 138.57 139.28 16244.0
2021-12-28  Live Cattle Future (front month) (February)   LEG2 139.32 139.72 138.45 139.40 19304.0
2021-12-29  Live Cattle Future (front month) (February)   LEG2 140.00 141.43 139.98 140.72 26245.0
2021-12-30  Live Cattle Future (front month) (February)   LEG2 140.28 140.62 139.85 139.98 18683.0
2021-12-31  Live Cattle Future (front month) (February)   LEG2 139.98 139.98 139.43 139.70 15003.0
2022-01-03  Live Cattle Future (front month) (February)   LEG2 139.78 140.40 138.88 138.93 19752.0
2022-01-04  Live Cattle Future (front month) (February)   LEG2 138.65 138.72 136.78 137.82 35656.0
2022-01-05  Live Cattle Future (front month) (February)   LEG2 138.00 138.32 136.88 137.25 24866.0
2022-01-06  Live Cattle Future (front month) (February)   LEG2 137.40 137.55 136.38 137.35 24741.0
2022-01-07  Live Cattle Future (front month) (February)   LEG2 137.35 137.70 136.57 137.32 29519.0
2022-01-10  Live Cattle Future (front month) (February)   LEG2 136.90 137.38 136.02 136.25 35305.0
2022-01-11  Live Cattle Future (front month) (February)   LEG2 136.28 138.18 136.25 137.68 36728.0
2022-01-12  Live Cattle Future (front month) (February)   LEG2 137.75 137.85 136.40 136.57 29913.0
2022-01-13  Live Cattle Future (front month) (February)   LEG2 136.85 137.25 136.65 137.00 26221.0
2022-01-14  Live Cattle Future (front month) (February)   LEG2 137.05 138.75 136.85 137.98 17822.0
2021-12-15    Live Cattle Future (second month) (April)   LEJ2 141.80 141.85 140.80 140.93  8138.0
2021-12-16    Live Cattle Future (second month) (April)   LEJ2 140.88 141.35 140.05 140.95  7889.0
2021-12-17    Live Cattle Future (second month) (April)   LEJ2 140.93 141.12 140.12 140.60  9373.0
2021-12-20    Live Cattle Future (second month) (April)   LEJ2 140.10 140.68 139.93 140.18 10557.0
2021-12-21    Live Cattle Future (second month) (April)   LEJ2 140.40 141.93 140.28 141.35 10294.0
2021-12-22    Live Cattle Future (second month) (April)   LEJ2 141.40 142.30 141.22 142.12  8404.0
2021-12-23    Live Cattle Future (second month) (April)   LEJ2 142.00 144.00 142.00 143.93 11703.0
2021-12-27    Live Cattle Futu

===== EXAMPLE 2 =====
      Date                                 Product Name Symbol   Open   High    Low  Close  Volume
2021-12-20  Live Cattle Future (front month) (February)   LEG2 135.93 136.55 135.50 135.98 20294.0
2021-12-21  Live Cattle Future (front month) (February)   LEG2 136.28 137.65 135.95 136.93 17615.0
2021-12-22  Live Cattle Future (front month) (February)   LEG2 136.93 137.57 136.70 137.38 13095.0
2021-12-23  Live Cattle Future (front month) (February)   LEG2 137.40 139.72 137.25 139.62 19977.0

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (7823 > 512). Running this sequence through the model will result in indexing errors

count     3143.000000
mean     12118.510022
std      11707.769667
min       2793.000000
50%       7435.000000
75%      12133.500000
90%      35953.000000
95%      36746.000000
99%      37755.660000
max      38392.000000
Name: input_length, dtype: float64
count    3143.000000
mean      131.379574
std        86.968900
min         6.000000
50%       113.000000
75%       169.500000
90%       257.000000
95%       320.900000
99%       393.000000
max       560.000000
Name: target_length, dtype: float64
Input > 512: 1.0
Target > 256: 0.10054088450524976
Raw table_data length (chars): 13166
      Date                                 Product Name Symbol   Open   High    Low  Close  Volume
2021-11-02  Live Cattle Future (front month) (December)   LEZ1 128.90 130.43 128.88 129.95 21275.0
2021-11-03  Live Cattle Future (front month) (December)   LEZ1 130.90 132.40 130.62 131.65 27572.0
2021-11-04  Live Cattle Future (front month) (December)   LEZ1 131.57 132.00 130.55 130.62 23398.0
2021-11-05  Live Cattle Future (front month) (December)   LEZ1 130.85 131.93 130.68 131.80 31050.0
2021-11-08  Live Cattle Future (front month) (December)   LEZ1 131.70 132.50 131.70 132.10 30902.0
2021-11-09  Live Cattle Future (front month) (December)   LEZ1 131.88 132.38 131.40 132.20 30503.0
2021-11-10  Live Cattle Future (front month) (December)   LEZ1 131.90 132.38 131.30 132.00 31903.0
2021-11-11  Live Cattle Future (front month) (December)   LEZ1 132.15 132.32 131.38 131.88 25671.0
2021-11-12  Live Cattle Future (front month) (December)   LEZ1 131.90 132.62 131.48 132.12 21703.0
2021-11-15  Live Cattle Future (front month) (December)   LEZ1 131.78 132.30 131.50 131.78 14062.0
2021-11-16  Live Cattle Future (front month) (December)   LEZ1 131.78 132.18 131.68 131.72 10213.0
2021-11-17  Live Cattle Future (front month) (December)   LEZ1 131.93 132.38 131.80 132.22 13364.0
2021-11-18  Live Cattle Future (front month) (December)   LEZ1 132.45 133.28 132.40 133.15  9596.0
2021-11-19  Live Cattle Future (front month) (December)   LEZ1 133.25 133.68 133.00 133.52  8783.0
2021-11-22  Live Cattle Future (front month) (December)   LEZ1 133.82 134.52 133.68 134.43  9629.0
2021-11-23  Live Cattle Future (front month) (December)   LEZ1 134.48 135.57 134.22 135.40  9547.0
2021-11-24  Live Cattle Future (front month) (December)   LEZ1 136.05 137.98 136.00 137.90 16978.0
2021-11-26  Live Cattle Future (front month) (December)   LEZ1 136.40 138.35 136.28 138.10  8984.0
2021-11-29  Live Cattle Future (front month) (December)   LEZ1 138.25 139.12 136.62 136.93 12045.0
2021-11-30  Live Cat
...
Number of rows in raw table_data: 132
count    3143.000000
mean      183.038180
std       150.757429
min        51.000000
25%        70.000000
50%       133.000000
75%       190.000000
max       515.000000
Name: raw_table_rows, dtype: float64
Date: 2021-11-02, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 128.9, High: 130.43, Low: 128.88, Close: 129.95, Volume: 21275.0 | Date: 2021-11-03, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 130.9, High: 132.4, Low: 130.62, Close: 131.65, Volume: 27572.0 | Date: 2021-11-04, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.57, High: 132.0, Low: 130.55, Close: 130.62, Volume: 23398.0 | Date: 2021-11-05, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 130.85, High: 131.93, Low: 130.68, Close: 131.8, Volume: 31050.0 | Date: 2021-11-08, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.7, High: 132.5, Low: 131.7, Close: 132.1, Volume: 30902.0 | Date: 2021-11-09, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.88, High: 132.38, Low: 131.4, Close: 132.2, Volume: 30503.0 | Date: 2021-11-10, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.9, High: 132.38, Low: 131.3, Close: 132.0, Volume: 31903.0 | Date: 2021-11-11, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 132.15, High: 132.32, Low: 131.38, Close: 131.88, Volume: 25671.0 | Date: 2021-11-12, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.9, High: 132.62, Low: 131.48, Close: 132.12, Volume: 21703.0 | Date: 2021-11-15, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.78, High: 132.3, Low: 131.5, Close: 131.78, Volume: 14062.0 | Date: 2021-11-16, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.78, High: 132.18, Low: 131.68, Close: 131.72, Volume: 10213.0 | Date: 2021-11-17, Product Name: Live Cattle Future (front month) (December), Symbol: LEZ1, Open: 131.93, High: 132.38, Low: 131.8, Close: 132.22, Volume: 13364.0 | Date: 2021-11-18, Product Name: Live C
(132, 8)
['Date', 'Product Name', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume']
         Date                                 Product Name Symbol    Open  \
0  2021-11-02  Live Cattle Future (front month) (December)   LEZ1  128.90
1  2021-11-03  Live Cattle Future (front month) (December)   LEZ1  130.90
2  2021-11-04  Live Cattle Future (front month) (December)   LEZ1  131.57
3  2021-11-05  Live Cattle Future (front month) (December)   LEZ1  130.85
4  2021-11-08  Live Cattle Future (front month) (December)   LEZ1  131.70

     High     Low   Close   Volume
0  130.43  128.88  129.95  21275.0
1  132.40  130.62  131.65  27572.0
2  132.00  130.55  130.62  23398.0
3  131.93  130.68  131.80  31050.0
4  132.50  131.70  132.10  30902.0
           Date                                Product Name Symbol    Open  \
127  2021-11-26  Feeder Cattle Future (third month) (April)   GFJ2  167.50
128  2021-11-29  Feeder Cattle Future (third month) (April)   GFJ2  169.88
129  2021-11-30  Feeder Cattle Future (third month) (April)   GFJ2  167.58
130  2021-12-01  Feeder Cattle Future (third month) (April)   GFJ2  168.82
131  2021-12-02  Feeder Cattle Future (third month) (April)   GFJ2  170.00

       High     Low   Close  Volume
127  170.40  167.35  169.88  1330.0
128  171.00  167.82  168.58  2057.0
129  169.85  167.25  168.82  2380.0
130  170.70  168.82  170.45  1681.0
131  171.00  169.62  170.90  1288.0
Date            0
Product Name    0
Symbol          0
Open            0
High            0
Low             0
Close           0
Volume          0
dtype: int64
count     3143.000000
mean      4772.636335
std       4057.868174
min       1297.000000
50%       3339.000000
75%       4992.000000
90%      12945.600000
95%      13324.800000
99%      13702.000000
max      14113.000000
Name: input_length, dtype: float64
Product: Live Cattle Future (front month) (December)
Symbol: LEZ1
Period start: 2021-11-02
Period end: 2021-12-02
Trading days: 132
Starting close: 129.95
Ending close: 170.90
Period high: 171.00
Period low: 128.88
Absolute price change: 40.95
Percentage price change: 31.51%
Daily return volatility: 1.25%
Maximum daily gain: 10.11%
Maximum daily loss: -4.69%
Average volume: 9696
Maximum volume: 31903
Minimum volume: 558
Overall price trend: Upward
(132, 8)
2021-11-02 00:00:00
2021-12-02 00:00:00
22
        Date                                 Product Name Symbol    Open  \
0 2021-11-02  Live Cattle Future (front month) (December)   LEZ1  128.90
1 2021-11-03  Live Cattle Future (front month) (December)   LEZ1  130.90
2 2021-11-04  Live Cattle Future (front month) (December)   LEZ1  131.57
3 2021-11-05  Live Cattle Future (front month) (December)   LEZ1  130.85
4 2021-11-08  Live Cattle Future (front month) (December)   LEZ1  131.70

     High     Low   Close   Volume
0  130.43  128.88  129.95  21275.0
1  132.40  130.62  131.65  27572.0
2  132.00  130.55  130.62  23398.0
3  131.93  130.68  131.80  31050.0
4  132.50  131.70  132.10  30902.0
          Date                                Product Name Symbol    Open  \
127 2021-11-26  Feeder Cattle Future (third month) (April)   GFJ2  167.50
128 2021-11-29  Feeder Cattle Future (third month) (April)   GFJ2  169.88
129 2021-11-30  Feeder Cattle Future (third month) (April)   GFJ2  167.58
130 2021-12-01  Feeder Cattle Future (third month) (April)   GFJ2  168.82
131 2021-12-02  Feeder Cattle Future (third month) (April)   GFJ2  170.00

       High     Low   Close  Volume
127  170.40  167.35  169.88  1330.0
128  171.00  167.82  168.58  2057.0
129  169.85  167.25  168.82  2380.0
130  170.70  168.82  170.45  1681.0
131  171.00  169.62  170.90  1288.0
        Date   Close   Volume
0 2021-11-02  129.95  21275.0
1 2021-11-03  131.65  27572.0
2 2021-11-04  130.62  23398.0
3 2021-11-05  131.80  31050.0
4 2021-11-08  132.10  30902.0
5 2021-11-09  132.20  30503.0
6 2021-11-10  132.00  31903.0
7 2021-11-11  131.88  25671.0
8 2021-11-12  132.12  21703.0
9 2021-11-15  131.78  14062.0
          Date   Close  Volume
122 2021-11-18  166.08  1267.0
123 2021-11-19  165.88  1283.0
124 2021-11-22  166.70   784.0
125 2021-11-23  168.02  1119.0
126 2021-11-24  169.80  1611.0
127 2021-11-26  169.88  1330.0
128 2021-11-29  168.58  2057.0
129 2021-11-30  168.82  2380.0
130 2021-12-01  170.45  1681.0
131 2021-12-02  170.90  1288.0
Date
2021-11-02    6
2021-11-03    6
2021-11-04    6
2021-11-05    6
2021-11-08    6
2021-11-09    6
2021-11-10    6
2021-11-11    6
2021-11-12    6
2021-11-15    6
Name: count, dtype: int64
[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/266/266_final_project/train_splitEDA.ipynb to python
[NbConvertApp] Writing 11999 bytes to /content/drive/MyDrive/Colab Notebooks/266/266_final_project/train_splitEDA.py
total 488542
-rw------- 1 root root    130451 Jul 24 18:14 266_final_project_Text_analysis_pb.ipynb
-rw------- 1 root root      9247 Jul 20 23:18 266_git_workflow.ipynb
-rw------- 1 root root    241736 Jul 29 00:34 model1_encoder-decoder.ipynb
drwx------ 6 root root      4096 Jul 28 23:33 models
drwx------ 2 root root      4096 Jul 25 02:38 t5_small_model1
-rw------- 1 root root  51883332 Jul 24 17:53 test_split.json
-rw------- 1 root root 249532501 Jul 17 19:32 train.json
-rw------- 1 root root     83924 Jul 25 15:52 train_splitEDA.ipynb
-rw------- 1 root root     12000 Jul 29 00:36 train_splitEDA.py
-rw------- 1 root root 198363259 Jul 24 17:53 train_split.json
Train rows: 3143
Test rows: 795

In [8]:
# %%capture
# %run -i "/content/drive/MyDrive/Colab Notebooks/266/266_final_project/train_splitEDA.py"

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (7823 > 512). Running this sequence through the model will result in indexing errors

In [9]:
# after = set(globals().keys())
# new_vars = after - before
# #variables from exported notebook above
# print(new_vars)

{'summarize_market_table', 'sample', 'parsed', 'token_length', 'test_file', 'linearize_table', 'before', 'test_df', 'build_encoder_input', 'sample_df', 'model_name', 'tokenizer', 'train_file', 'summary', '__file__', 'i', '_i9', 'train_df', 'save_dir', 'linearize_table_compact', 'StringIO', '_i8'}

### Build Encoder input and decoder targets
- Encoder processes the structured financial data withfull context, no generation order needed.
- Decoder generates text token by token
- Cross-attention lets the decoder ground each generated word back in the specific numbers/facts from the encoder. This will be helpful to check the factual consistency of hypothesis.
- Bidirectional encoder:The encoder will use full, non-causal self-attention. It needs the full self attention to see the entire table at once to build a complete representation.
- So, no masking the tokens on the input side.
- Decoder: The decoder will use causal masked self-attention since it generates autoregressively and can't peek at future output tokens.
- Models to use : **T5/ BART**

In [10]:
def build_encoder_input(row):
    return (
        "Generate a financial market report.\n\n"
        f"Instruction:\n"
        f"{row['instruction']}\n\n"
        f"Market summary:\n"
        f"{row['market_summary']}"
    )

In [11]:
for df in (train_df, test_df):
    df["market_summary"] = df["table_data"].apply(summarize_market_table)
    df["encoder_input"] = df.apply(build_encoder_input, axis=1)
    df["decoder_target"] = df["report"]

print(train_df[["encoder_input", "decoder_target"]].head(2))

                                       encoder_input  \
0  Generate a financial market report.\n\nInstruc...
1  Generate a financial market report.\n\nInstruc...

                                      decoder_target
0  Cattle futures posted moderate to strong gains...
1  Cattle prices are trying to turn higher, as th...

In [12]:
# Inspect lengths before choosing truncation limits.
train_df["input_length"] = train_df["encoder_input"].apply(token_length)
train_df["target_length"] = train_df["decoder_target"].apply(token_length)

print("Input lengths")
display(train_df["input_length"].describe(percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]))

print("\nTarget lengths")
display(train_df["target_length"].describe(percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]))

print("\nTargets longer than 384 tokens:", (train_df["target_length"] > 384).sum())
print("Percentage longer than 384:", (train_df["target_length"] > 384).mean())

Input lengths

count    3143.000000
mean      174.361120
std         6.731297
min       148.000000
50%       176.000000
75%       178.000000
90%       181.000000
95%       183.000000
99%       185.000000
max       188.000000
Name: input_length, dtype: float64

Target lengths

count    3143.000000
mean      131.379574
std        86.968900
min         6.000000
50%       113.000000
75%       169.500000
90%       257.000000
95%       320.900000
99%       393.000000
max       560.000000
Name: target_length, dtype: float64

Targets longer than 384 tokens: 42
Percentage longer than 384: 0.013363028953229399

In [13]:
print("Targets > 128:",(train_df["target_length"] > 128).mean())
print("Targets > 256:",(train_df["target_length"] > 256).mean())

Targets > 128: 0.42666242443525293
Targets > 256: 0.10054088450524976

In [14]:
print("ENCODER INPUT\n")
print(train_df.iloc[0]["encoder_input"])

print("\n")
print("DECODER TARGET\n")
print(train_df.iloc[0]["decoder_target"])

ENCODER INPUT

Generate a financial market report.

Instruction:
Please act as an expert financial market analyst. Please generate a market report:
1. by analyzing the historical market data provided.
2. following the market report example provided.

Market summary:
Product: Live Cattle Future (front month) (December)
Symbol: LEZ1
Period start: 2021-11-02
Period end: 2021-12-02
Trading days: 132
Starting close: 129.95
Ending close: 170.90
Period high: 171.00
Period low: 128.88
Absolute price change: 40.95
Percentage price change: 31.51%
Daily return volatility: 1.25%
Maximum daily gain: 10.11%
Maximum daily loss: -4.69%
Average volume: 9696
Maximum volume: 31903
Minimum volume: 558
Overall price trend: Upward


DECODER TARGET

Cattle futures posted moderate to strong gains as cash trade stayed supportive in the live cattle market. Dec live cattle gained 1.650 to 137.650, and Feb cattle were .975 higher to 139.575. Feeders saw mixed, to mostly higher market as Jan feeders were slightly lower, losing .050 to 165.775. Light trade was seen across all of cattle country with trade ranging $140-142. This was steady to $3 higher than last week in most areas, and with the Dec futures trading well below those level, help get the buyers into the cattle futures. The afternoon close in retail values will be key going into the open tomorrow. Feeder cattle saw moderate gains at the cash feeder market has been trending higher. The Cash feeder index was .26 lower to 161.34, but has been trending higher. The seasonality makes the market cautious and the price action has signaled a near-term top. The stronger cash trade helped support prices, but prices are consolidating at this weeks trading range.

In [15]:
print("Targets > 384:",(train_df["target_length"] > 384).sum())
print("Percentage > 384:",(train_df["target_length"] > 384).mean())

Targets > 384: 42
Percentage > 384: 0.013363028953229399

### Shared configuration and Hugging Face datasets

### Model
1. Fine-tuned pretrained T5-small - Load T5 model : "t5-small"  - Chunk long sequences. Split long documents into 512‑token chunks and process them sequentially.
2. t5 base
2. t5_tokenizer = AutoTokenizer.from_pretrained("google-t5/t5-large")
3. t5_model = AutoModelForSeq2SeqLM.from_pretrained("google-t5/t5-large")
4. LongT5 (4k–16k tokens) - not possible due to cost constraints

#### Convert Pandas DataFrames into Hugging Face datasets

wrap train_df/test_df in a HuggingFace Dataset, apply tokenize_batch, and fine-tune with Seq2SeqTrainer

Dataset + Seq2SeqTrainer training loop

In [20]:
MODEL_NAME = "google-t5/t5-small"
MAX_INPUT_LENGTH = 256
MAX_TARGET_LENGTH = 384
GENERATION_KWARGS = {
    "max_new_tokens": MAX_TARGET_LENGTH,
    "num_beams": 4,
    "early_stopping": True,
    }

In [ ]:
MODEL_DIRS = {
    "zero_shot": os.path.join(BASE_DIR, "models", "t5-small-zero-shot"),
    "finetuned": os.path.join(BASE_DIR, "models", "t5-small-finetuned"),
    }
for path in MODEL_DIRS.values():
    os.makedirs(path, exist_ok=True)

In [18]:
train_dataset = Dataset.from_pandas(
    train_df[["encoder_input", "decoder_target"]],
    preserve_index=False,)

test_dataset = Dataset.from_pandas(
    test_df[["encoder_input", "decoder_target"]],
    preserve_index=False,)

test_inputs = test_df["encoder_input"].tolist()
references = test_df["decoder_target"].tolist()

print(train_dataset)
print(test_dataset)

Dataset({
    features: ['encoder_input', 'decoder_target'],
    num_rows: 3143
})
Dataset({
    features: ['encoder_input', 'decoder_target'],
    num_rows: 795
})

### Shared batched prediction function

In [19]:
def generate_predictions_batched(model,tokenizer,texts,batch_size=8,
                                 max_input_length=MAX_INPUT_LENGTH,generation_kwargs=None,):

    """Generate predictions in batches for zero shot or fine tuned seq2seq models"""

    if generation_kwargs is None:
        generation_kwargs = GENERATION_KWARGS

    model = model.to(DEVICE)
    model.eval()
    predictions = []

    for start in range(0, len(texts), batch_size):
        batch_texts = texts[start:start + batch_size]

        encoded = tokenizer(
            batch_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_input_length,
        )
        encoded = {key: value.to(DEVICE) for key, value in encoded.items()}

        with torch.no_grad():
            generated_ids = model.generate(**encoded, **generation_kwargs,)

        batch_predictions = tokenizer.batch_decode(
            generated_ids,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=True,
        )
        predictions.extend(batch_predictions)

    return predictions

### Shared eval metrics  function

In [23]:
rouge_metric = evaluate.load("rouge")
sacrebleu_metric = evaluate.load("sacrebleu")
meteor_metric = evaluate.load("meteor")
bertscore_metric = evaluate.load("bertscore")

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Downloading builder script: 0.00B [00:00, ?B/s]

In [24]:
def evaluate_predictions(predictions, references, model_label):
    """Return one flat dictionary suitable for a model-level results DataFrame."""
    rouge_scores = rouge_metric.compute(
        predictions=predictions,
        references=references,
        use_stemmer=True,)

    bleu_scores = sacrebleu_metric.compute(
        predictions=predictions,
        references=[[reference] for reference in references],)

    meteor_scores = meteor_metric.compute(
        predictions=predictions,
        references=references,)

    bert_scores = bertscore_metric.compute(
        predictions=predictions,
        references=references,
        lang="en",)

    return {
        "model": model_label,
        "rouge1": rouge_scores["rouge1"],
        "rouge2": rouge_scores["rouge2"],
        "rougeL": rouge_scores["rougeL"],
        "sacrebleu": bleu_scores["score"],
        "meteor": meteor_scores["meteor"],
        "bertscore_precision": float(np.mean(bert_scores["precision"])),
        "bertscore_recall": float(np.mean(bert_scores["recall"])),
        "bertscore_f1": float(np.mean(bert_scores["f1"])),
    }

In [29]:
# Every model will append 1 metrics row and 1 prediction set
metrics_rows = []
prediction_frames = []

### T5 zero-shot baseline:
running the pretrained, non-fine-tuned T5-small on test set before comparing it to fine-tuned version.

1. Load pretrained tokenizer and model  
2. Generate batched predictions directly from raw test strings  
3. Evaluate predictions  
4. Append metrics and predictions to shared DataFrames  

A data collator is not required for zero-shot generation because there is no Trainer or training batch.

### Tokenize
Apply to both train and test datasets : We can see input_ids, attention_mask, labels

Run again when loading from checkpoint, because tokenized datasets are not saved automatically.

In [25]:
# load the zero-shot model
zero_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
zero_model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(DEVICE)

print("Loaded zero-shot model:", MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

Loaded zero-shot model: google-t5/t5-small

In [26]:
# Run this once to save the zero-shot model
zero_model.save_pretrained(MODEL_DIRS["zero_shot"])
zero_tokenizer.save_pretrained(MODEL_DIRS["zero_shot"])
print("Saved zero-shot checkpoint to:", MODEL_DIRS["zero_shot"])

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved zero-shot checkpoint to: /content/drive/MyDrive/Colab Notebooks/266/266_final_project/models/t5-small-zero-shot

### Generate zero-shot predictions

In [27]:
zero_predictions = generate_predictions_batched(
    model=zero_model,
    tokenizer=zero_tokenizer,
    texts=test_inputs,
    batch_size=8,
)

print("Generated predictions:", len(zero_predictions))
print("\nExample prediction:\n", zero_predictions[0])
print("\nReference:\n", references[0])

Generated predictions: 795

Example prediction:
 : 36.77 Percentage price change: 25.63% Daily return volatility: 1.37% Maximum daily gain: 13.01% Maximum daily loss: -2.85% Average volume: 8873 Maximum volume: 35921 Minimum volume: 510 Overall price trend: Upward

Reference:
 Oct live cattle gained 0.075 to 151.675, closing with a new contract high for the seventh straight day, and Dec slipped 0.825 to 153.300. Feeders were mostly lower with the exception of the front month with expiration on the 27th. Nov feeders traded 1.225 lower to 177.925. December cattle posted a new contract high early in the session, before turning lower on the day. This could be a sign of consolidation, or a loss of momentum after a strong rally. Cash trade was still undeveloped on Tuesday, but expectations are for cash trade to trend higher week over week. Southern asking prices are $152, with undefined bids. Beef retail values have jumped in the last two days. At midday Tuesday, Choice carcasses traded 3.95 higher to 261.87 and Select was 1.79 higher to 227.40 on light movement of 52 loads. This gave Choice carcasses over a $10.00 jump with Monday and Tuesday’s midday trade. The Choice/Select spread remains strong at 34.47 in a window this spread typically tightens. In the near term, the fundamentals are still pointing higher as the cattle market is trending to new highs or poise to challenge those highs, but the market may be ready for a pause and wait for a strong cash confirmation.

## Evaluate and collect zero-shot results

In [30]:
zero_metrics = evaluate_predictions(
    predictions=zero_predictions,
    references=references,
    model_label="t5-small-zero-shot",
)
metrics_rows.append(zero_metrics)

zero_output_df = test_df.copy()
zero_output_df["model"] = "t5-small-zero-shot"
zero_output_df["prediction"] = zero_predictions
prediction_frames.append(
    zero_output_df[["model", "encoder_input", "decoder_target", "prediction"]]
)

display(pd.DataFrame([zero_metrics]))

,model,rouge1,rouge2,rougeL,sacrebleu,meteor,bertscore_precision,bertscore_recall,bertscore_f1
0,t5-small-zero-shot,0.057857,0.001057,0.040656,0.00402,0.026264,0.771497,0.780427,0.775841

In [31]:
# Free GPU memory before loading the training model.
del zero_model
torch.cuda.empty_cache() if torch.cuda.is_available() else None

# Fine-tuned T5-small

Order:

1. Load a fresh tokenizer and pretrained model  
2. Tokenize train and test datasets  
3. Create the dynamic data collator  
4. Define training arguments and Trainer  
5. Train and save the model  
6. Generate batched predictions using the saved/best model  
7. Evaluate and append results

WE're not using padding="max_length" to ensure that padded label tokens dont contribute to the loss. The data collator will dynamically pad each batch.

The tokenizer, data collator, and model are included in the same fine-tuning pipeline.

In [32]:
# Loading a fresh model and tokenizer for fine-tuning

ft_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
ft_model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

print("Loaded fresh model for fine-tuning:", MODEL_NAME)

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

Loaded fresh model for fine-tuning: google-t5/t5-small

### Tokenize train and test datasets

In [33]:
def tokenize_batch(examples):
    model_inputs = ft_tokenizer(
        examples["encoder_input"],
        max_length=MAX_INPUT_LENGTH,
        truncation=True,)

    labels = ft_tokenizer(
        text_target=examples["decoder_target"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True,)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_train = train_dataset.map(
    tokenize_batch,
    batched=True,
    remove_columns=train_dataset.column_names,)

tokenized_test = test_dataset.map(
    tokenize_batch,
    batched=True,
    remove_columns=test_dataset.column_names,)

print(tokenized_train)
print(tokenized_test)
print(tokenized_train[0].keys())

Map:   0%|          | 0/3143 [00:00<?, ? examples/s]

Map:   0%|          | 0/795 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 3143
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 795
})
dict_keys(['input_ids', 'attention_mask', 'labels'])

### Create the data collator
Instead of manually padding every example to max_input_length, data collater will handle the padding dynamically per batch

In [34]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer=ft_tokenizer,
    model=ft_model,
    padding="longest",
    label_pad_token_id=-100,)

print(data_collator)

DataCollatorForSeq2Seq(tokenizer=T5Tokenizer(name_or_path='google-t5/t5-small', vocab_size=32100, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, added_tokens_decoder={
	0: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32000: AddedToken("<extra_id_99>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32001: AddedToken("<extra_id_98>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32002: AddedToken("<extra_id_97>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32003: AddedToken("<extra_id_96>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32004: AddedToken("<extra_id_95>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32005: AddedToken("<extra_id_94>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32006: AddedToken("<extra_id_93>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32007: AddedToken("<extra_id_92>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32008: AddedToken("<extra_id_91>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32009: AddedToken("<extra_id_90>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32010: AddedToken("<extra_id_89>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32011: AddedToken("<extra_id_88>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32012: AddedToken("<extra_id_87>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32013: AddedToken("<extra_id_86>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32014: AddedToken("<extra_id_85>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32015: AddedToken("<extra_id_84>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32016: AddedToken("<extra_id_83>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32017: AddedToken("<extra_id_82>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32018: AddedToken("<extra_id_81>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32019: AddedToken("<extra_id_80>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32020: AddedToken("<extra_id_79>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32021: AddedToken("<extra_id_78>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32022: AddedToken("<extra_id_77>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32023: AddedToken("<extra_id_76>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32024: AddedToken("<extra_id_75>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32025: AddedToken("<extra_id_74>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32026: AddedToken("<extra_id_73>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32027: AddedToken("<extra_id_72>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32028: AddedToken("<extra_id_71>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32029: AddedToken("<extra_id_70>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32030: AddedToken("<extra_id_69>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32031: AddedToken("<extra_id_68>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32032: AddedToken("<extra_id_67>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32033: AddedToken("<extra_id_66>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32034: AddedToken("<extra_id_65>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32035: AddedToken("<extra_id_64>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32036: AddedToken("<extra_id_63>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32037: AddedToken("<extra_id_62>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32038: AddedToken("<extra_id_61>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32039: AddedToken("<extra_id_60>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32040: AddedToken("<extra_id_59>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32041: AddedToken("<extra_id_58>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32042: AddedToken("<extra_id_57>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32043: AddedToken("<extra_id_56>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32044: AddedToken("<extra_id_55>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32045: AddedToken("<extra_id_54>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32046: AddedToken("<extra_id_53>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32047: AddedToken("<extra_id_52>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32048: AddedToken("<extra_id_51>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32049: AddedToken("<extra_id_50>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32050: AddedToken("<extra_id_49>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32051: AddedToken("<extra_id_48>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32052: AddedToken("<extra_id_47>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32053: AddedToken("<extra_id_46>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32054: AddedToken("<extra_id_45>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32055: AddedToken("<extra_id_44>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32056: AddedToken("<extra_id_43>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32057: AddedToken("<extra_id_42>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32058: AddedToken("<extra_id_41>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32059: AddedToken("<extra_id_40>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32060: AddedToken("<extra_id_39>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32061: AddedToken("<extra_id_38>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32062: AddedToken("<extra_id_37>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32063: AddedToken("<extra_id_36>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32064: AddedToken("<extra_id_35>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32065: AddedToken("<extra_id_34>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32066: AddedToken("<extra_id_33>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32067: AddedToken("<extra_id_32>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32068: AddedToken("<extra_id_31>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32069: AddedToken("<extra_id_30>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32070: AddedToken("<extra_id_29>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32071: AddedToken("<extra_id_28>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32072: AddedToken("<extra_id_27>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32073: AddedToken("<extra_id_26>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32074: AddedToken("<extra_id_25>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32075: AddedToken("<extra_id_24>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32076: AddedToken("<extra_id_23>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32077: AddedToken("<extra_id_22>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32078: AddedToken("<extra_id_21>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32079: AddedToken("<extra_id_20>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32080: AddedToken("<extra_id_19>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32081: AddedToken("<extra_id_18>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32082: AddedToken("<extra_id_17>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32083: AddedToken("<extra_id_16>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32084: AddedToken("<extra_id_15>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32085: AddedToken("<extra_id_14>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32086: AddedToken("<extra_id_13>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32087: AddedToken("<extra_id_12>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32088: AddedToken("<extra_id_11>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32089: AddedToken("<extra_id_10>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32090: AddedToken("<extra_id_9>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32091: AddedToken("<extra_id_8>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32092: AddedToken("<extra_id_7>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32093: AddedToken("<extra_id_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32094: AddedToken("<extra_id_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32095: AddedToken("<extra_id_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32096: AddedToken("<extra_id_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32097: AddedToken("<extra_id_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32098: AddedToken("<extra_id_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32099: AddedToken("<extra_id_0>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}), model=T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
), padding='longest', max_length=None, pad_to_multiple_of=None, label_pad_token_id=-100, return_tensors='pt')

### Training arguments and Trainer

In [ ]:
# # from transformers import Seq2SeqTrainingArguments
# #  loaded from check point -do not run again

# training_args = Seq2SeqTrainingArguments(
#     output_dir="./t5-small-financial-commentary",

#     eval_strategy="epoch",
#     save_strategy="epoch",
#     learning_rate=5e-5,
#     per_device_train_batch_size=8,
#     per_device_eval_batch_size=8,
#     weight_decay=0.01,
#     num_train_epochs=5,
#     predict_with_generate=True,
#     logging_steps=50,
#     save_total_limit=2,
#     load_best_model_at_end=True,
#     metric_for_best_model="eval_loss",
#     greater_is_better=False,
#     fp16=True, # for T4 GPU
#     report_to="none"
# )

In [35]:
training_args = Seq2SeqTrainingArguments(
    output_dir=os.path.join(BASE_DIR, "checkpoints", "t5-small-finetuning"),
    learning_rate=3e-4,
    lr_scheduler_type="linear",
    num_train_epochs=10,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=20,

    predict_with_generate=True,
    generation_max_length=MAX_TARGET_LENGTH,
    generation_num_beams=4,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2,

    fp16=torch.cuda.is_available(),
    report_to="none",
    seed=SEED,
)

Create the trainer

In [36]:
trainer = Seq2SeqTrainer(
    model=ft_model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    processing_class=ft_tokenizer,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],)

print("Trainer created")

Trainer created

In [37]:
print(type(tokenized_train))
print(type(tokenized_test))

<class 'datasets.arrow_dataset.Dataset'>
<class 'datasets.arrow_dataset.Dataset'>

### Model Training

In [38]:
#  run once, load from check point -do not run again
train_result = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

In [39]:
display(pd.DataFrame([train_result.metrics]))

,train_runtime,train_samples_per_second,train_steps_per_second,total_flos,train_loss,epoch
0,727.5464,43.2,5.402,1.508984e+15,3.065431,10.0

### Save fine tuned model

In [40]:
trainer.save_model(MODEL_DIRS["finetuned"])
ft_tokenizer.save_pretrained(MODEL_DIRS["finetuned"])

with open(
    os.path.join(MODEL_DIRS["finetuned"], "training_metrics.json"),
    "w",
) as file:
    json.dump(train_result.metrics, file, indent=2)

print("Saved fine-tuned model to:", MODEL_DIRS["finetuned"])

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved fine-tuned model to: /content/drive/MyDrive/Colab Notebooks/266/266_final_project/models/t5-small-finetuned

In [ ]:
# load checkpoint in a later session

# ft_tokenizer = AutoTokenizer.from_pretrained(MODEL_DIRS["finetuned"])
# ft_model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_DIRS["finetuned"]).to(DEVICE)

# print("Loaded fine-tuned checkpoint.")

### Generate fine-tuned predictions in batches

In [41]:
fine_tuned_model = trainer.model.to(DEVICE)

fine_tuned_predictions = generate_predictions_batched(
    model=fine_tuned_model,
    tokenizer=ft_tokenizer,
    texts=test_inputs,
    batch_size=8,
)

print("Generated predictions:", len(fine_tuned_predictions))
print("\nExample prediction:\n", fine_tuned_predictions[0])
print("\nReference:\n", references[0])

Generated predictions: 795

Example prediction:
 Oct live cattle gained 0.025 to 142.750, and Oct cattle gained 0.025 to 143.750. Feeders saw mixed trade on Tuesday, as Oct feeders gained 0.025 to 143.750. Oct feeders traded 0.025 higher to 180.750. For the week, Oct feeders gained 0.025, and Oct added 0.025. For the week, Oct feeders were 0.025 higher. October feeders were 0.025 higher, and June added 0.025. October feeders are trading at a small discount to the index. The Feeder Cattle Cash Index was softer on the day, gaining 0.025 to 143.25. The cash market was supportive, but the market is still in an uptrend. The cattle market is still in an uptrend, but the market may be looking for direction.

Reference:
 Oct live cattle gained 0.075 to 151.675, closing with a new contract high for the seventh straight day, and Dec slipped 0.825 to 153.300. Feeders were mostly lower with the exception of the front month with expiration on the 27th. Nov feeders traded 1.225 lower to 177.925. December cattle posted a new contract high early in the session, before turning lower on the day. This could be a sign of consolidation, or a loss of momentum after a strong rally. Cash trade was still undeveloped on Tuesday, but expectations are for cash trade to trend higher week over week. Southern asking prices are $152, with undefined bids. Beef retail values have jumped in the last two days. At midday Tuesday, Choice carcasses traded 3.95 higher to 261.87 and Select was 1.79 higher to 227.40 on light movement of 52 loads. This gave Choice carcasses over a $10.00 jump with Monday and Tuesday’s midday trade. The Choice/Select spread remains strong at 34.47 in a window this spread typically tightens. In the near term, the fundamentals are still pointing higher as the cattle market is trending to new highs or poise to challenge those highs, but the market may be ready for a pause and wait for a strong cash confirmation.

### Evaluate and append fine_tuned_model results

In [42]:
fine_tuned_metrics = evaluate_predictions(
    predictions=fine_tuned_predictions,
    references=references,
    model_label="t5-small-finetuned",
)
metrics_rows.append(fine_tuned_metrics)

fine_tuned_output_df = test_df.copy()
fine_tuned_output_df["model"] = "t5-small-finetuned"
fine_tuned_output_df["prediction"] = fine_tuned_predictions
prediction_frames.append(
    fine_tuned_output_df[["model", "encoder_input", "decoder_target", "prediction"]]
)

display(pd.DataFrame([fine_tuned_metrics]))

,model,rouge1,rouge2,rougeL,sacrebleu,meteor,bertscore_precision,bertscore_recall,bertscore_f1
0,t5-small-finetuned,0.272943,0.096536,0.203133,6.403039,0.17776,0.876687,0.840908,0.858156

### Combine and save all experiment results

In [44]:
metrics_df = pd.DataFrame(metrics_rows)
predictions_df = pd.concat(prediction_frames, ignore_index=True)

display(metrics_df)
display(predictions_df.head())

metrics_path = os.path.join(BASE_DIR, "model_metrics.csv")
predictions_path = os.path.join(BASE_DIR, "model_predictions.csv")

metrics_df.to_csv(metrics_path, index=False)
predictions_df.to_csv(predictions_path, index=False)

print("Saved model metrics to:", metrics_path)
print("Saved predictions to:", predictions_path)

,model,rouge1,rouge2,rougeL,sacrebleu,meteor,bertscore_precision,bertscore_recall,bertscore_f1
0,t5-small-zero-shot,0.057857,0.001057,0.040656,0.004020,0.026264,0.771497,0.780427,0.775841
1,t5-small-finetuned,0.272943,0.096536,0.203133,6.403039,0.177760,0.876687,0.840908,0.858156

,model,encoder_input,decoder_target,prediction
0,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,"Oct live cattle gained 0.075 to 151.675, closi...",: 36.77 Percentage price change: 25.63% Daily ...
1,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,Oct live cattle slipped .225 to 151.450 with e...,": 37.77 Percentage price change: 26,32% Daily ..."
2,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,"The cattle market came under selling pressure,...",: 142.72 Absolute price change: 36.88 Percenta...
3,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,"The cattle market was choppy on Friday, finish...",": 37.33 Percentage price change: 26,10% Daily ..."
4,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,October live cattle went off the board today a...,: 179.45 Period high: 182.38 Period low: 146.7...

## T5-base Model

In [45]:
# Free memory from T5-small before loading T5-base
del ft_model, trainer
torch.cuda.empty_cache() if torch.cuda.is_available() else None

### Model name and directory

In [46]:
MODEL_NAME = "google-t5/t5-base"

In [47]:
# Shared configs are same as t5-small
# MAX_INPUT_LENGTH = 256
# MAX_TARGET_LENGTH = 384
# GENERATION_KWARGS = {
#     "max_new_tokens": MAX_TARGET_LENGTH,
#     "num_beams": 4,
#     "early_stopping": True,
# }

MODEL_DIRS = {
    "zero_shot": os.path.join(BASE_DIR, "models", "t5-base-zero-shot"),
    "finetuned": os.path.join(BASE_DIR, "models", "t5-base-finetuned"),
}

1. Need to change batch_size to 4 instead of 8 for T4 GPU memory management. T5-base is 3 times more parameters than T5-small (220M vs. 60M), so it needs more VRAM per example during both training and generation.

2. Also will add gradient_accumulation_steps=2 in Seq2SeqTrainingArguments so the effective batch size, which drives the gradient update, stays at 8, and that will match the t5-small.

### Load T5-base model and zero shot it

In [48]:
zero_tokenizer_base = AutoTokenizer.from_pretrained("google-t5/t5-base")
zero_model_base = AutoModelForSeq2SeqLM.from_pretrained("google-t5/t5-base").to(DEVICE)
print("Loaded zero-shot model:", MODEL_NAME)

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  892MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Loaded zero-shot model: google-t5/t5-base

In [49]:
# save the zero-t5-base model locally, run once.

zero_model_base.save_pretrained(MODEL_DIRS["zero_shot"])
zero_tokenizer_base.save_pretrained(MODEL_DIRS["zero_shot"])
print("Saved zero-shot base checkpoint to:", MODEL_DIRS["zero_shot"])

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved zero-shot base checkpoint to: /content/drive/MyDrive/Colab Notebooks/266/266_final_project/models/t5-base-zero-shot

### generate zero-shot base predictions

In [50]:
zero_pred_base = generate_predictions_batched(
    model=zero_model_base,
    tokenizer=zero_tokenizer_base,
    texts=test_inputs,
    batch_size=4,)

print("Generated predictions:", len(zero_pred_base))
print("\nExample prediction:\n", zero_pred_base[0])
print("\nReference:\n", references[0])

Generated predictions: 795

Example prediction:
 142.72 Period high: 182.38 Period low: 142.72 Period high: 182.38 Period low: 142.72 Absolute price change: 36.77 Percentage price change: 25.63% Daily return volatility: 1.37% Maximum daily gain: 13.01% Maximum daily loss: -2.85% Average volume: 8873 Maximum volume: 35921 Minimum volume: 510 Average volume: 8873 Maximum volume: 8873 Minimum volume: 35921 Minimum volume: 510 Average volume:

Reference:
 Oct live cattle gained 0.075 to 151.675, closing with a new contract high for the seventh straight day, and Dec slipped 0.825 to 153.300. Feeders were mostly lower with the exception of the front month with expiration on the 27th. Nov feeders traded 1.225 lower to 177.925. December cattle posted a new contract high early in the session, before turning lower on the day. This could be a sign of consolidation, or a loss of momentum after a strong rally. Cash trade was still undeveloped on Tuesday, but expectations are for cash trade to trend higher week over week. Southern asking prices are $152, with undefined bids. Beef retail values have jumped in the last two days. At midday Tuesday, Choice carcasses traded 3.95 higher to 261.87 and Select was 1.79 higher to 227.40 on light movement of 52 loads. This gave Choice carcasses over a $10.00 jump with Monday and Tuesday’s midday trade. The Choice/Select spread remains strong at 34.47 in a window this spread typically tightens. In the near term, the fundamentals are still pointing higher as the cattle market is trending to new highs or poise to challenge those highs, but the market may be ready for a pause and wait for a strong cash confirmation.

### Evaluate zero_model_base and append results

In [52]:
zero_metrics_base = evaluate_predictions(
    predictions=zero_pred_base,
    references=references,
    model_label="t5-base-zero-shot",
)
metrics_rows.append(zero_metrics_base)

zero_output_df_base = test_df.copy()
zero_output_df_base["model"] = "t5-base-zero-shot"
zero_output_df_base["prediction"] = zero_pred_base
prediction_frames.append(
    zero_output_df_base[["model", "encoder_input", "decoder_target", "prediction"]]
)

display(pd.DataFrame([zero_metrics_base]))

,model,rouge1,rouge2,rougeL,sacrebleu,meteor,bertscore_precision,bertscore_recall,bertscore_f1
0,t5-base-zero-shot,0.057949,0.003745,0.040108,0.224147,0.032917,0.752887,0.77749,0.764631

## Fine-tuned T5-base

In [53]:
# free memory before fine-tuning
del zero_model_base
torch.cuda.empty_cache() if torch.cuda.is_available() else None

In [54]:
# load fresh model and tokenizer

ft_tokenizer_base = AutoTokenizer.from_pretrained(MODEL_NAME)
ft_model_base = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

print("Loaded fresh model for fine-tuning:", MODEL_NAME)

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

Loaded fresh model for fine-tuning: google-t5/t5-base

### Tokenize train and test datasets

In [55]:
def tokenize_batch(examples):
    model_inputs = ft_tokenizer_base(
        examples["encoder_input"],
        max_length=MAX_INPUT_LENGTH,
        truncation=True,)

    labels = ft_tokenizer_base(
        text_target=examples["decoder_target"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True,)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_train = train_dataset.map(
    tokenize_batch,
    batched=True,
    remove_columns=train_dataset.column_names,)

tokenized_test = test_dataset.map(
    tokenize_batch,
    batched=True,
    remove_columns=test_dataset.column_names,)

print(tokenized_train)
print(tokenized_test)
print(tokenized_train[0].keys())

Map:   0%|          | 0/3143 [00:00<?, ? examples/s]

Map:   0%|          | 0/795 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 3143
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 795
})
dict_keys(['input_ids', 'attention_mask', 'labels'])

In [56]:
# data collator
data_collator = DataCollatorForSeq2Seq(
    tokenizer=ft_tokenizer_base,
    model=ft_model_base,
    padding="longest",
    label_pad_token_id=-100,
)

print(data_collator)

DataCollatorForSeq2Seq(tokenizer=T5Tokenizer(name_or_path='google-t5/t5-base', vocab_size=32100, model_max_length=1000000000000000019884624838656, padding_side='right', truncation_side='right', special_tokens={'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, added_tokens_decoder={
	0: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32000: AddedToken("<extra_id_99>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32001: AddedToken("<extra_id_98>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32002: AddedToken("<extra_id_97>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32003: AddedToken("<extra_id_96>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32004: AddedToken("<extra_id_95>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32005: AddedToken("<extra_id_94>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32006: AddedToken("<extra_id_93>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32007: AddedToken("<extra_id_92>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32008: AddedToken("<extra_id_91>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32009: AddedToken("<extra_id_90>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32010: AddedToken("<extra_id_89>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32011: AddedToken("<extra_id_88>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32012: AddedToken("<extra_id_87>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32013: AddedToken("<extra_id_86>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32014: AddedToken("<extra_id_85>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32015: AddedToken("<extra_id_84>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32016: AddedToken("<extra_id_83>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32017: AddedToken("<extra_id_82>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32018: AddedToken("<extra_id_81>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32019: AddedToken("<extra_id_80>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32020: AddedToken("<extra_id_79>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32021: AddedToken("<extra_id_78>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32022: AddedToken("<extra_id_77>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32023: AddedToken("<extra_id_76>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32024: AddedToken("<extra_id_75>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32025: AddedToken("<extra_id_74>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32026: AddedToken("<extra_id_73>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32027: AddedToken("<extra_id_72>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32028: AddedToken("<extra_id_71>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32029: AddedToken("<extra_id_70>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32030: AddedToken("<extra_id_69>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32031: AddedToken("<extra_id_68>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32032: AddedToken("<extra_id_67>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32033: AddedToken("<extra_id_66>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32034: AddedToken("<extra_id_65>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32035: AddedToken("<extra_id_64>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32036: AddedToken("<extra_id_63>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32037: AddedToken("<extra_id_62>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32038: AddedToken("<extra_id_61>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32039: AddedToken("<extra_id_60>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32040: AddedToken("<extra_id_59>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32041: AddedToken("<extra_id_58>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32042: AddedToken("<extra_id_57>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32043: AddedToken("<extra_id_56>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32044: AddedToken("<extra_id_55>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32045: AddedToken("<extra_id_54>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32046: AddedToken("<extra_id_53>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32047: AddedToken("<extra_id_52>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32048: AddedToken("<extra_id_51>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32049: AddedToken("<extra_id_50>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32050: AddedToken("<extra_id_49>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32051: AddedToken("<extra_id_48>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32052: AddedToken("<extra_id_47>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32053: AddedToken("<extra_id_46>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32054: AddedToken("<extra_id_45>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32055: AddedToken("<extra_id_44>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32056: AddedToken("<extra_id_43>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32057: AddedToken("<extra_id_42>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32058: AddedToken("<extra_id_41>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32059: AddedToken("<extra_id_40>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32060: AddedToken("<extra_id_39>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32061: AddedToken("<extra_id_38>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32062: AddedToken("<extra_id_37>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32063: AddedToken("<extra_id_36>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32064: AddedToken("<extra_id_35>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32065: AddedToken("<extra_id_34>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32066: AddedToken("<extra_id_33>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32067: AddedToken("<extra_id_32>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32068: AddedToken("<extra_id_31>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32069: AddedToken("<extra_id_30>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32070: AddedToken("<extra_id_29>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32071: AddedToken("<extra_id_28>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32072: AddedToken("<extra_id_27>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32073: AddedToken("<extra_id_26>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32074: AddedToken("<extra_id_25>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32075: AddedToken("<extra_id_24>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32076: AddedToken("<extra_id_23>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32077: AddedToken("<extra_id_22>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32078: AddedToken("<extra_id_21>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32079: AddedToken("<extra_id_20>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32080: AddedToken("<extra_id_19>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32081: AddedToken("<extra_id_18>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32082: AddedToken("<extra_id_17>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32083: AddedToken("<extra_id_16>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32084: AddedToken("<extra_id_15>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32085: AddedToken("<extra_id_14>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32086: AddedToken("<extra_id_13>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32087: AddedToken("<extra_id_12>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32088: AddedToken("<extra_id_11>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32089: AddedToken("<extra_id_10>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32090: AddedToken("<extra_id_9>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32091: AddedToken("<extra_id_8>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32092: AddedToken("<extra_id_7>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32093: AddedToken("<extra_id_6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32094: AddedToken("<extra_id_5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32095: AddedToken("<extra_id_4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32096: AddedToken("<extra_id_3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32097: AddedToken("<extra_id_2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32098: AddedToken("<extra_id_1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32099: AddedToken("<extra_id_0>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}), model=T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
), padding='longest', max_length=None, pad_to_multiple_of=None, label_pad_token_id=-100, return_tensors='pt')

### Training args with smaller batch size

keeping all args same as t5-small, except batch_size and adding gradient_accumulation_steps=2, to keep the training set-up comparable between the two models.

Note: learning rate is same as t5-small for a controlled  comparision. However, T5-base can sometimes be less tolerant of high learning rates. After the first epoch if training and validation loss become unstable or produces nans or validation performance worsens, I'll rerun with lower learning rate 1e-4.

In [58]:
training_args = Seq2SeqTrainingArguments(
    output_dir=os.path.join(BASE_DIR, "checkpoints", "t5-base-finetuning"),
    learning_rate=3e-4,
    lr_scheduler_type="linear",
    num_train_epochs=10,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2, # effective batch size = 4 * 2 = 8, same as T5-small

    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=20,

    predict_with_generate=True,
    generation_max_length=MAX_TARGET_LENGTH,
    generation_num_beams=4,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2,

    fp16=torch.cuda.is_available(),
    report_to="none",
    seed=SEED,
)

### Create Trainer

In [59]:
trainer = Seq2SeqTrainer(
    model=ft_model_base,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    processing_class=ft_tokenizer_base,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

print("Trainer created")

Trainer created

In [60]:
train_result_base = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

,train_runtime,train_samples_per_second,train_steps_per_second,total_flos,train_loss,epoch
0,1659.1883,18.943,2.369,4.707951e+15,5.022631,7.0

In [61]:
display(pd.DataFrame([train_result_base.metrics]))

,train_runtime,train_samples_per_second,train_steps_per_second,total_flos,train_loss,epoch
0,1659.1883,18.943,2.369,4.707951e+15,5.022631,7.0

In [64]:
#  save finetuned model

trainer.save_model(MODEL_DIRS["finetuned"])
ft_tokenizer_base.save_pretrained(MODEL_DIRS["finetuned"])

with open(
    os.path.join(MODEL_DIRS["finetuned"], "training_metrics.json"),
    "w",
) as file:
    json.dump(train_result_base.metrics, file, indent=2)

print("Saved fine-tuned model to:", MODEL_DIRS["finetuned"])

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved fine-tuned model to: /content/drive/MyDrive/Colab Notebooks/266/266_final_project/models/t5-base-finetuned

In [63]:
print(ft_model_base.config.model_type)
print(ft_model_base.config.d_model)

t5
768

In [ ]:
# load checkpoint in a later session
# ft_tokenizer_base = AutoTokenizer.from_pretrained(MODEL_DIRS["finetuned"])
# ft_model_base = AutoModelForSeq2SeqLM.from_pretrained(
#     MODEL_DIRS["finetuned"]
# ).to(DEVICE)
# print("Loaded fine-tuned checkpoint.")

### Generate fine-tuned predictions in batches

In [65]:
fine_tuned_model_base = trainer.model.to(DEVICE)

fine_tuned_pred_base = generate_predictions_batched(
    model=fine_tuned_model_base,
    tokenizer=ft_tokenizer_base,
    texts=test_inputs,
    batch_size=4, # lower batch size similar to training
)

print("Generated predictions:", len(fine_tuned_pred_base))
print("\nExample prediction:\n", fine_tuned_pred_base[0])
print("\nReference:\n", references[0])

Generated predictions: 795

Example prediction:
 Cattle futures saw mixed trade to end the week, as the cattle market saw selling pressure to start the week. Oct live cattle gained.075 to 142.750, and Dec live cattle gained.075 to 143.750. Feeders saw mixed trade as Oct feeders traded.075 lower to 179.375. October feeders traded.075 lower to 179.375. October feeders traded.075 lower to 179.375. October feeders traded.075 lower on the week. October live cattle futures are still trading at a discount to the cash market, which could be a limiting factor to the live cattle market. The cash market has been trending lower this week, but prices are still trading at a discount to the cash market. Retail values were firmer at midday (Choice: -1.09 to 256.29, Select: -1.29 to 249.29) with demand light at 61 midday loads. Feeder cattle saw strong buying strength as choice carcasses gained.27 to 264.27. Feeder cattle saw strong buying strength as choice carcasses gained.27 to 264.27. Feeder cattle saw strong buying strength as the feeder cattle market pushed through the 200-day moving average. The Feeder Cattle Cash Index was.27 lower to 174.27. The cattle market is still in an uptrend, but the market is still in an uptrend.

Reference:
 Oct live cattle gained 0.075 to 151.675, closing with a new contract high for the seventh straight day, and Dec slipped 0.825 to 153.300. Feeders were mostly lower with the exception of the front month with expiration on the 27th. Nov feeders traded 1.225 lower to 177.925. December cattle posted a new contract high early in the session, before turning lower on the day. This could be a sign of consolidation, or a loss of momentum after a strong rally. Cash trade was still undeveloped on Tuesday, but expectations are for cash trade to trend higher week over week. Southern asking prices are $152, with undefined bids. Beef retail values have jumped in the last two days. At midday Tuesday, Choice carcasses traded 3.95 higher to 261.87 and Select was 1.79 higher to 227.40 on light movement of 52 loads. This gave Choice carcasses over a $10.00 jump with Monday and Tuesday’s midday trade. The Choice/Select spread remains strong at 34.47 in a window this spread typically tightens. In the near term, the fundamentals are still pointing higher as the cattle market is trending to new highs or poise to challenge those highs, but the market may be ready for a pause and wait for a strong cash confirmation.

### Evaluate and append fine-tuned results

In [ ]:
# zero_metrics_base = evaluate_predictions(
#     predictions=zero_pred_base,
#     references=references,
#     model_label="t5-base-zero-shot",
# )
# metrics_rows.append(zero_metrics_base)

# zero_output_df_base = test_df.copy()
# zero_output_df_base["model"] = "t5-base-zero-shot"
# zero_output_df_base["prediction"] = zero_pred_base
# prediction_frames.append(
#     zero_output_df_base[["model", "encoder_input", "decoder_target", "prediction"]]
# )

# display(pd.DataFrame([zero_metrics_base]))

In [66]:
fine_tuned_metrics_base = evaluate_predictions(
    predictions=fine_tuned_pred_base,
    references=references,
    model_label="t5-base-finetuned",
)
metrics_rows.append(fine_tuned_metrics_base)

fine_tuned_output_df = test_df.copy()
fine_tuned_output_df["model"] = "t5-base-finetuned"
fine_tuned_output_df["prediction"] = fine_tuned_pred_base
prediction_frames.append(
    fine_tuned_output_df[["model", "encoder_input", "decoder_target", "prediction"]]
)

display(pd.DataFrame([fine_tuned_metrics]))

,model,rouge1,rouge2,rougeL,sacrebleu,meteor,bertscore_precision,bertscore_recall,bertscore_f1
0,t5-small-finetuned,0.272943,0.096536,0.203133,6.403039,0.17776,0.876687,0.840908,0.858156

In [67]:
#  combine and save al experiments results
metrics_df = pd.DataFrame(metrics_rows)
predictions_df = pd.concat(prediction_frames, ignore_index=True)

display(metrics_df)
display(predictions_df.head())

,model,rouge1,rouge2,rougeL,sacrebleu,meteor,bertscore_precision,bertscore_recall,bertscore_f1
0,t5-small-zero-shot,0.057857,0.001057,0.040656,0.004020,0.026264,0.771497,0.780427,0.775841
1,t5-small-finetuned,0.272943,0.096536,0.203133,6.403039,0.177760,0.876687,0.840908,0.858156
2,t5-base-zero-shot,0.057949,0.003745,0.040108,0.224147,0.032917,0.752887,0.777490,0.764631
3,t5-base-zero-shot,0.057949,0.003745,0.040108,0.224147,0.032917,0.752887,0.777490,0.764631
4,t5-base-finetuned,0.286315,0.108871,0.213307,7.417643,0.194107,0.876012,0.846746,0.860887

,model,encoder_input,decoder_target,prediction
0,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,"Oct live cattle gained 0.075 to 151.675, closi...",: 36.77 Percentage price change: 25.63% Daily ...
1,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,Oct live cattle slipped .225 to 151.450 with e...,": 37.77 Percentage price change: 26,32% Daily ..."
2,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,"The cattle market came under selling pressure,...",: 142.72 Absolute price change: 36.88 Percenta...
3,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,"The cattle market was choppy on Friday, finish...",": 37.33 Percentage price change: 26,10% Daily ..."
4,t5-small-zero-shot,Generate a financial market report.\n\nInstruc...,October live cattle went off the board today a...,: 179.45 Period high: 182.38 Period low: 146.7...

In [68]:
metrics_path = os.path.join(BASE_DIR, "model_metrics.csv")
predictions_path = os.path.join(BASE_DIR, "model_predictions.csv")

metrics_df.to_csv(metrics_path, index=False)
predictions_df.to_csv(predictions_path, index=False)

print("Saved model metrics to:", metrics_path)
print("Saved predictions to:", predictions_path)

Saved model metrics to: /content/drive/MyDrive/Colab Notebooks/266/266_final_project/model_metrics.csv
Saved predictions to: /content/drive/MyDrive/Colab Notebooks/266/266_final_project/model_predictions.csv

### Evaluation
- Output commentary Vs. Reference commentary
- Output commentary vs. Underlying numerical facts

- Evaluation Metrics
  - Lexical
  - ROUGE
  - BLEU

- Semantic
  - BERTScore

- Factual grounding
  - LLM as a judge